file = open("file2", "w+")
file.write("programmer wants to work on python project")
file.flush()
print("Current position after write:", file.tell())
file.seek(0)
print("After seek(0), position:", file.tell())
content = file.read()
print("Content:", content)
file.close()